### ISSUE TITLE
Should README specify unitless values for `minLineHeight` and `maxLineHeight`?

### ISSUE THREAD

**Issue by tinymachine** [glyphic-co/textblock#24]
It looks like the script will only accept line-height parameter values that are unitless numbers (not the keyword `normal`, or values that include length-based units). I might be missing it, but I don't see any reference to this in the README, so might be helpful to include that.

**Comment by theorosendorf** [comment]
Good point. And perfect for this round. I'll edit the readme. In the future we should maybe consider also allowing length-based units for line height.

**Comment by tinymachine** [comment]
Sounds good, but just a heads-up that the PR I'm working includes changes to the readme (for the new param names), so that may require a little work to merge.

**Comment by theorosendorf** [comment]
Cool, I’ll wait for it then. Thanks Mihira!

**Comment by tinymachine** [comment]
My pleasure - it's a cool script you've written, thank you for sharing it!
