### ISSUE TITLE
Format variable names to be more legible when stacked

### ISSUE THREAD

**Issue by theorosendorf** [glyphic-co/textblock#34]
Perhaps something more like this?:

```
minWidth
maxWidth
minWidth_FontSize
maxWidth_FontSize
minWidth_LineHeight
maxWidth_LineHeight
minWidth_VariableGrade
maxWidth_VariableGrade
```

**Comment by tinymachine** [comment]
Was thinking about same thing. An alternative might be to put the type attribute first, which might make for sensible groupings (especially if the `units` param changes to specify which attribute it applies to):

```
minWidth
maxWidth
fontSize_minWidth
fontSize_maxWidth
fontSize_units
lineHeight_minWidth
lineHeight_maxWidth
variableGrade_minWidth
variableGrade_maxWidth
```

**Comment by theorosendorf** [comment]
This is an interesting issue. `minWidth` and `maxWidth` are just so similar. Reversing the logical order, i.e. `fontSize_minWidth` seems weird and I think makes scanning more difficult. Perhaps a mix of underscore and capitalization for the second part helps separate the two? It kind of turns min/maxWidth into a bullet point, moving it out of the way to its own column.

@traviskochel, @jessevdp, @anexasajoop, I'm curious what you guys might think about this.

Here’s what I propose:

```
minWidth
maxWidth
minWidth_FontSize
maxWidth_FontSize
fontSize_Units
minWidth_LineHeight
maxWidth_LineHeight
minWidth_VariableGrade
maxWidth_VariableGrade
```

Maybe this one is less good?

```
minWidth
maxWidth
minWidth_fontSize
maxWidth_fontSize
fontSize_units
minWidth_lineHeight
maxWidth_lineHeight
minWidth_variableGrade
maxWidth_variableGrade
```

And how it is currently:

```
minWidth
maxWidth
minWidthFontSize
maxWidthFontSize
fontSizeUnits
minWidthLineHeight
maxWidthLineHeight
minWidthVariableGrade
maxWidthVariableGrade
```

**Comment by theorosendorf** [comment]
Hey @tinymachine – do I have this right for an interim adjustment? Thanks!

https://github.com/glyphic-co/textblock/blob/6292c01eb958b2003d6f98b5adf5dc4dd527559b/src/textblock.js#L16-L39

https://github.com/glyphic-co/textblock/tree/more-legible-variable-names

**Comment by tinymachine** [comment]
@theorosendorf That looks exactly right to me, but I didn't test it myself. To make sure it's working, you might want to create a new test case in demo.html that uses the interim param names that you're deprecating (`min/maxWidthFontSize`, etc.). Does that make sense?
